### ISSUE TITLE
Migracion

### ISSUE THREAD

**Issue by daeiouabc** [pasosdeJesus/sivel2#2]
Buen dia.

Estoy intentando configurar el aplicativo en un ambiente de desarrollo. las dependencias estan instaladas, las bases de datos creadas, como estoy sobre el repositorio de sivel2 no es necesario crear los modelos y controladores de la guia y voy directamente a la creacion de la estructura de la base de datos.Estoy ejecutando en la base de datos `sivel2gen_des` el script `structure.sql` y me aparece el error adjunto en el pantallazo 

![image](https://user-images.githubusercontent.com/5685675/37248090-608dbe36-2496-11e8-9616-33403915defa.png)

entiendo que no poermite crear la codificacion de la linea 30 

`CREATE COLLATION es_co_utf_8 (lc_collate = 'es_CO.UTF-8', lc_ctype = 'es_CO.UTF-8');`

Es necesario configuracion adicional sobre la base de datos? Quedo atento.

**Comment by daeiouabc** [comment]
Me apresure a enviarles el mensaje, veo que el script hace referencia a la codificiacion 'es_CO.UTF-8'. y como no estoy usando **adJ** entonces  no cuento con esa codificacion, estoy buscando en el script de instalacion de adJ y no veo donde añade ese "locale", voy a seguir revisando, quedo atento.

**Comment by vtamara** [comment]
Intente remplazando es-CO.UTF-8 por el nombre del locale para Colombia del sistema operativo que usa (ver https://www.postgresql.org/docs/9.1/static/sql-createcollation.html  )

Por ejemplo en Ubuntu sería es_CO.utf8 (aunque no he usado SIVeL 2 en Ubuntu).

De la bitacora que puso, parece que se está ignorando ese error, así que debería operar aún sin ese locale  (aunque podría tener problemas con tildes y eñes).

Bendiciones

**Comment by vtamara** [comment]
Por el momento cerraré este caso (issue), dado que no ocurre en la plataforma recomendada. Pero por favor continúe escribiendo aquí para seguir ayudandole en su plataforma (Linux Mint?)

**Comment by vtamara** [comment]
Otra solución que es la usada en travis es crear el locale con el nombre que se espera:

sudo locale-gen --no-archive es_CO.UTF-8
